print("Measure 26-207")
print(" -\"Portland Public Schools Measure\"")
print(" -Levy Renewal to Maintain Teaching Positions and Classroom Supports")
print(" -The measure renews the levy that was approved by voters in 2014.")
print("\t -A YES VOTE renews a property tax levy of $1.99 per $1,000,")
print("\t  allocated to public education for five years.")
print("\t -A NO VOTE is a vote against renewing the property tax levy,")
print("\t  allowing the tax to expire.")